FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGVudnZhci1vcGVyYXRvcgpkZXNjcmlwdGlvbjogIlRoZSBPcGVy\
YXRvciBpbml0aWFsaXNlcyBjb250YWluZXIgRW52aXJvbm1lbnQgVmFyaWFibGVzIGZyb20gQ29u\
ZmlnTWFwcyIKYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbAptZXRhZGF0YToKICBkaXNw\
bGF5TmFtZTogRW52aXJvbm1lbnQgVmFyaWFibGUgT3BlcmF0b3IKICBpbWFnZVVybDogImh0dHBz\
Oi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9zandvb2RtYW4vZW52LXZhci1hcGIvbWFzdGVy\
L2ljb24uc3ZnP3Nhbml0aXplPXRydWUiCiAgcHJvdmlkZXJEaXNwbGF5TmFtZTogIlJlZCBIYXQs\
IEluYy4iCnBsYW5zOgogIC0gbmFtZTogZGVmYXVsdAogICAgZGVzY3JpcHRpb246IFRoaXMgcGxh\
biBkZXBsb3lzIHRoZSBFbnZpcm9tZW50IFZhcmlhYmxlIG9wZXJhdG9yCiAgICBmcmVlOiBUcnVl\
CiAgICBtZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6CiAgICAtIG5hbWU6IGFkbWluX3VzZXIK\
ICAgICAgdGl0bGU6IE9wZW5zaGlmdCBBZG1pbiBVc2VyCiAgICAgIHR5cGU6IHN0cmluZwogICAg\
ICByZXF1aXJlZDogdHJ1ZQogICAgLSBuYW1lOiBhZG1pbl9wYXNzd29yZAogICAgICB0aXRsZTog\
T3BlbnNoaWZ0IEFkbWluIFBhc3N3b3JkCiAgICAgIHR5cGU6IHN0cmluZwogICAgICBkaXNwbGF5\
X3R5cGU6IHBhc3N3b3JkCiAgICAgIHJlcXVpcmVkOiB0cnVlCg=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb

